Repository LongMetal-Robotics/Infinite-Recharge, pull requests merged in 2020-02, with the labels that each got.

#19 I did the thing. Please see attached issues
  src/main/java/org/longmetal/ControlPanel.java
  vendordeps/Phoenix.json
  vendordeps/REVColorSensorV3.json
Labels: enhancement, help wanted

#12 i love everything i see on this paper
  src/main/java/org/longmetal/Constants.java
  src/main/java/org/longmetal/Shooter.java
Labels: enhancement

#18 It's the cliiiiimb
  src/main/java/org/longmetal/Climb.java
  src/main/java/org/longmetal/Constants.java
Labels: enhancement

#11 makes the intake exist
  src/main/java/org/longmetal/Constants.java
  src/main/java/org/longmetal/Intake.java
Labels: enhancement

#37 Shuffleboard Enablers
  src/main/java/frc/robot/Robot.java
  src/main/java/org/longmetal/Climb.java
  src/main/java/org/longmetal/Constants.java
  src/main/java/org/longmetal/Intake.java
  src/main/java/org/longmetal/Shooter.java
  src/main/java/org/longmetal/exception/SubsystemDisabledException.java
  src/main/java/org/longmetal/exception/SubsystemException.java
  src/main/java/org/longmetal/exception/SubsystemUninitializedException.java
  src/main/java/org/longmetal/subsystem/Climb.java
  src/main/java/org/longmetal/subsystem/ControlPanel.java
  src/main/java/org/longmetal/subsystem/DriveTrain.java
  src/main/java/org/longmetal/subsystem/Intake.java
  src/main/java/org/longmetal/subsystem/ShootFormula.java
  src/main/java/org/longmetal/subsystem/Shooter.java
  src/main/java/org/longmetal/subsystem/Subsystem.java
  src/main/java/org/longmetal/subsystem/SubsystemManager.java
Labels: bug

#38 Methods for climb
  src/main/java/org/longmetal/subsystem/Climb.java
Labels: enhancement

#45 Implement listener
  src/main/java/frc/robot/Robot.java
Labels: maintenance

#50 Pneumatics
  src/main/java/frc/robot/Robot.java
  src/main/java/org/longmetal/Constants.java
  src/main/java/org/longmetal/subsystem/Climb.java
  src/main/java/org/longmetal/subsystem/ControlPanel.java
  src/main/java/org/longmetal/subsystem/Pneumatics.java
Labels: question
